// <auto-generated />
using MVCBookPractice_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBookPractice_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231009234749_SeedBookTable")]
    partial class SeedBookTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCBookPractice_Model.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISBN = "123B4HC",
                            Price = 15.99m,
                            Title = "Pawn of Prophecy"
                        },
                        new
                        {
                            Id = 2,
                            ISBN = "7734JT1",
                            Price = 35.99m,
                            Title = "A Court of Thorns and Roses"
                        },
                        new
                        {
                            Id = 3,
                            ISBN = "713GJK12",
                            Price = 4.99m,
                            Title = "Bonded by Thorns"
                        },
                        new
                        {
                            Id = 4,
                            ISBN = "123IYM",
                            Price = 1.99m,
                            Title = "Remarried Empress"
                        },
                        new
                        {
                            Id = 5,
                            ISBN = "947HD99",
                            Price = 13.99m,
                            Title = "Wilde Fae: Lord of Nightmare"
                        },
                        new
                        {
                            Id = 6,
                            ISBN = "341HNB4",
                            Price = 4.99m,
                            Title = "His Darkest Craving"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
